Repository cmu-delphi/www-covidcast, pull requests merged in 2021-05, with the labels that each got.

#929 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#935 feat: link to published r package version
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#938 improve search component
  src/components/RegionDatePicker.svelte
  src/components/Search.svelte
  src/components/searchHelpers.ts
  src/modes/classic/AddAnother.svelte
  src/modes/classic/Overview.svelte
  src/modes/dashboard/DashboardParameters.svelte
  src/modes/dashboard/config/RegionPicker.svelte
  src/modes/exportdata/ExportData.svelte
  src/modes/indicator-status/IndicatorStatusOverview.svelte
  src/modes/lab/PCP.svelte
  src/modes/landing/Landing.svelte
Labels: enhancement

#940 track dashboard interactions
  src/modes/dashboard/DashboardParameters.svelte
  src/modes/dashboard/state.ts
Labels: enhancement

#941 build: update dependencies
  cypress/integration/utils/epidata.js
  package-lock.json
  package.json
  src/data/annotations.ts
  src/data/fetchData.ts
  src/data/indicatorInfo.ts
  src/data/meta.ts
  src/data/regions.ts
  src/data/utils.ts
  src/modes/classic/Overview.svelte
  src/modes/classic/components/legends/BubbleLegend.svelte
  src/modes/dashboard/state.ts
  src/modes/summary/IndicatorTable.svelte
  src/specs/lineSpec.ts
  src/specs/mapSpec.ts
  src/stores/allSensors.ts
  src/stores/constants.ts
  src/stores/index.ts
  src/stores/urlHandler.ts
  tsconfig.eslint.json
Labels: chore

#944 fix: county regions are not found
  src/data/regions.ts
  src/stores/descriptions.raw.txt
  src/stores/questions.raw.txt
Labels: bug

#945 improve Vega performance
  src/components/vega/Vega.svelte
  src/modes/indicator-status/IndicatorCountyMap.svelte
  src/modes/indicator-status/IndicatorCountyMapTooltip.svelte
  src/specs/mapSpec.ts
  src/specs/shapefiles/README.md
  src/specs/shapefiles/county_highres.json
  src/specs/shapefiles/state_highres.json
Labels: enhancement

#948 feat: add link to source code
  src/modes/landing/Landing.svelte
Labels: enhancement
