Repository cmu-delphi/www-covidcast, pull requests merged in 2021-11, with the labels that each got.

#1069 fix showing rest of state tooltip
  src/components/TrendIndicator.svelte
  src/data/trend.ts
  src/modes/summary/CasesOverview.svelte
  src/specs/mapSpec.ts
  src/stores/descriptions.raw.txt
  src/stores/index.ts
Labels: bug

#1071 hotfix loading jhu-csse trends
  package-lock.json
  package.json
  src/modes/summary/Summary.svelte
Labels: bug

#1073 chore: sync main->dev
  package-lock.json
  package.json
  src/modes/summary/Summary.svelte
Labels: chore

#1065 set default date to today()-1
  src/blocks/IndicatorWarning.svelte
  src/data/TimeFrame.ts
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/stores/index.ts
Labels: feedback required, v3

#1079 show latest available data in indicator table
  src/components/KPIChange.svelte
  src/components/SensorDatePicker2.svelte
  src/data/trend.ts
  src/modes/summary/IndicatorTable.svelte
Labels: enhancement

#1068 update signals
  src/components/TrendIndicator.svelte
  src/data/trend.ts
  src/modes/summary/CasesOverview.svelte
  src/modes/summary/IndicatorTable.svelte
  src/stores/descriptions.raw.txt
  src/stores/index.ts
Labels: enhancement

#1077 update dependencies and setup
  .github/workflows/ci.yml
  .github/workflows/release_main.yml
  .github/workflows/update_gdocs_data.yml
  jest.config.js
  package-lock.json
  package.json
  src/components/HexGrid/HexGrid.svelte
  src/components/SensorDatePicker2.svelte
  src/data/meta.ts
  src/modes/exportdata/ExportData.svelte
  src/wrapper/_customize.scss
  src/wrapper/layout/_layouts.scss
  webpack.config.js
Labels: chore
