Repository cmu-delphi/www-covidcast, pull requests merged in 2021-08, with the labels that each got.

#992 fix: msa mixed signal
  src/blocks/HistoryLineChart.svelte
Labels: bug

#994 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#959 New Indicator Status Overview
  src/blocks/HistoryLineChart.svelte
  src/components/GeoLevelBadge.svelte
  src/components/SensorBadges.svelte
  src/components/SensorSourceSearch.svelte
  src/components/SourceBadges.svelte
  src/data/api.ts
  src/data/fetchTriple.ts
  src/data/indicatorInfo.ts
  src/index.html
  src/modes/data-anomalies/AnnotationTable.svelte
  src/modes/data-anomalies/DataAnomalies.svelte
  src/modes/index.ts
  src/modes/indicator-status/DataAnomalies.svelte
  src/modes/indicator-status/IndicatorBackfill.svelte
  src/modes/indicator-status/IndicatorCoverageChart.svelte
  src/modes/indicator-status/IndicatorData.svelte
  src/modes/indicator-status/IndicatorSignal.svelte
  src/modes/indicator-status/IndicatorSignalTable.svelte
  src/modes/indicator-status/IndicatorSource.svelte
  src/modes/indicator-status/IndicatorStatusOverview.svelte
  src/modes/indicator-status/IndicatorStatusTable.svelte
  src/modes/indicator-status/data.ts
  src/modes/modes.js
  src/specs/lineSpec.ts
  src/stores/DataFetcher.ts
  webpack.config.js
Labels: enhancement

#997 fix active flag + filter out weekly signals
  src/data/api.ts
  src/data/meta.ts
  src/modes/indicator-status/IndicatorStatusTable.svelte
Labels: bug

#998 feat: allow lazy evaluation of sensor param for generic pages
  src/modes/dashboard/DashboardParameters.svelte
  src/modes/dashboard/config/RegionPicker.svelte
  src/modes/dashboard/utils.ts
  src/modes/index.ts
  src/modes/modes.js
  src/stores/index.ts
Labels: bug

#999 New indicator status page revisions from approval process
  .husky/pre-commit
  src/data/meta.ts
  src/modes/indicator-status/IndicatorSignal.svelte
  src/modes/indicator-status/IndicatorStatusTable.svelte
Labels: enhancement

#1001 fix neighbors and disable in survey view
  src/blocks/HistoryLineChart.svelte
  src/blocks/RegionHexMap.svelte
  src/data/fetchData.ts
  src/modes/survey-results/SurveyQuestion.svelte
  src/modes/survey-results/SurveyResults.svelte
Labels: enhancement

#1003 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore
