Repository cmu-delphi/www-covidcast, pull requests merged in 2021-04, with the labels that each got.

#888 build: fix gitpod config
  .gitpod.yml
Labels: chore

#898 fix: parsing on indicator status dates
  src/data/indicatorInfo.js
Labels: bug

#894 Encode visible indicator in hash
  src/data/indicatorInfo.js
  src/modes/indicator-status/IndicatorStatusOverview.svelte
  src/modes/indicator-status/IndicatorStatusTable.svelte
  src/stores/index.js
  src/stores/urlHandler.js
Labels: enhancement

#896 Add annotations to export page
  src/data/annotations.js
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#899 Add simple expandable line chart
  src/modes/mobile/HistoryLineChart.svelte
  src/modes/mobile/MobileIndicatorOverview.svelte
  src/modes/mobile/MobileOverview.svelte
  src/modes/mobile/common.css
Labels: enhancement

#900 Add nation/hhs support in COVIDcast classic
  src/components/MapBox/AMapBoxWrapper.js
  src/data/fetchData.js
  src/maps/geo.js
  src/maps/index.js
  src/maps/infos.js
  src/maps/processed/README.md
  src/maps/processed/cities.csv.js
  src/maps/processed/hhs.csv.js
  src/maps/processed/hhs.topojson.json
  src/maps/processed/nation.topojson.json
  src/maps/related.js
  src/modes/lab/CountyRelated.svelte
  src/modes/lab/StateHTMLMatrix.svelte
  src/modes/mobile/HistoryLineChart.svelte
  src/modes/mobile/RegionHexMap.svelte
  src/modes/overview/AddAnother.svelte
  src/modes/overview/Overview.svelte
  src/modes/top10/Top10.svelte
  src/specs/mapSpec.js
  src/specs/shapefiles/README.md
  src/specs/shapefiles/hhs.json
  src/stores/constants.js
  src/stores/index.js
  src/stores/params.js
  src/theme.js
Labels: enhancement

#893 Annotation Overview Table
  src/index.html
  src/modes/data-anomalies/AnnotationTable.svelte
  src/modes/data-anomalies/DataAnomalies.svelte
  src/modes/index.js
  src/modes/indicator-status/IndicatorStatusTable.svelte
  src/modes/mobile/GeoTable.svelte
  src/modes/mobile/IndicatorTable.svelte
  src/modes/mobile/components/SortColumnIndicator.svelte
  src/modes/mobile/components/tableUtils.js
  src/stores/dataSourceLookup.js
  src/stores/params.js
  webpack.config.js
Labels: enhancement

#878 Indicator Correlation Page
  package-lock.json
  package.json
  src/components/Search.svelte
  src/components/Vega.svelte
  src/components/tooltipUtils.js
  src/components/vegaFactory.js
  src/data/__test__/testData.js
  src/data/correlation.js
  src/data/correlation.spec.js
  src/data/correlationUtils.js
  src/data/utils.js
  src/data/utils.spec.js
  src/global.css
  src/index.html
  src/modes/correlation/CorrelationTooltip.svelte
  src/modes/correlation/IndicatorCorrelation.svelte
  src/modes/correlation/IndicatorCorrelationChart.svelte
  src/modes/correlation/LagChart.svelte
  src/modes/exportdata/ExportData.svelte
  src/modes/index.js
  src/modes/indicator-status/IndicatorStatusOverview.svelte
  src/modes/landing/Landing.svelte
  src/modes/mobile/HistoryLineChart.svelte
  src/modes/mobile/IndicatorAbout.svelte
  src/modes/mobile/IndicatorCorrelation.svelte
  src/modes/mobile/IndicatorDropdown.svelte
  src/modes/mobile/MobileIndicatorOverview.svelte
  src/modes/mobile/MobileOverview.svelte
  src/modes/mobile/common.css
  src/modes/mobile/components/AboutSection.svelte
  src/modes/mobile/components/WarningBanner.svelte
  src/modes/single/SensorCard.svelte
  src/modes/survey/Survey.svelte
  src/modes/survey/SurveyParameters.svelte
  src/modes/survey/SurveyQuestion.svelte
  src/specs/commonSpec.js
  src/specs/lineSpec.js
  src/stores/constants.js
  src/stores/index.js
  src/stores/params.js
  webpack.config.js
Labels: enhancement

#905 fix: correlation table lag rendering
  src/data/correlation.js
  src/data/correlationUtils.js
Labels: bug

#907 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#909 ci(fix): another try of cross repo PRs
  .github/workflows/release_main.yml
  .github/workflows/update_gdocs_data.yml
Labels: chore

#910 fix: mega-counties are not shown
  src/maps/infos.js
Labels: bug

#914 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#915 build(deps): update dependencies
  package-lock.json
  package.json
  webpack.config.js
Labels: chore

#922 fix: data anomalies reference link
  src/modes/data-anomalies/AnnotationTable.svelte
Labels: bug

#923 add warnings for common missing data
  src/blocks/IndicatorWarning.svelte
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/stores/constants.spec.ts
  src/stores/constants.ts
Labels: enhancement

#924 add hint about data freshness
  src/blocks/MaxDateHint.svelte
  src/components/Calendar/Datepicker.svelte
  src/components/RegionDatePicker.svelte
  src/components/SensorDatePicker2.svelte
  src/components/UIKitHint.svelte
  src/data/meta.ts
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/modes/summary/HighlightIndicators.svelte
  src/modes/summary/Summary.svelte
  src/modes/survey-results/SurveyQuestion.svelte
  src/modes/survey-results/SurveyResults.svelte
  src/stores/constants.ts
  src/stores/index.ts
  src/stores/params.ts
  src/stores/stats.ts
Labels: enhancement
