Repository cmu-delphi/www-covidcast, pull requests merged in 2021-06, with the labels that each got.

#951 feat: simplify R covidcast library example
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#953 update dependencies
  jest.config.js
  package-lock.json
  package.json
  src/modes/index.ts
  src/modes/indicator-status/store.ts
  src/modes/modes.d.ts
  src/modes/modes.js
  src/wrapper/_customize.scss
Labels: chore

#954 feat: switch to /anomalies endpoint
  netlify.toml
  src/data/annotations.ts
  src/data/api.ts
  webpack.config.js
Labels: enhancement

#956 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#958 fix: reused vega spec is not in sync
  src/components/vega/Vega.svelte
Labels: bug

#957 feat: improve data source names for meta 2.0 guesses
  src/data/dataSourceLookup.ts
  src/data/meta.ts
Labels: enhancement

#965 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#963 fix: trend change for 0 base value
  src/data/trend.ts
Labels: bug

#967 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#970 fix: disable show all on mobile
  src/blocks/HistoryLineChart.svelte
Labels: bug
