Repository cmu-delphi/www-covidcast, pull requests merged in 2021-07, with the labels that each got.

#971 feat: rename to CTIS results
  src/index.html
  src/modes/landing/Landing.svelte
  src/modes/modes.js
  src/modes/survey-results/SurveyResults.svelte
  src/stores/questions.raw.txt
Labels: enhancement

#975 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#978 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#960 sheet-based meta data preparation
  package-lock.json
  package.json
  src/components/SensorBadges.svelte
  src/components/SourceBadges.svelte
  src/data/api.ts
  src/data/meta.ts
  src/modes/dashboard/configResolver.ts
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#980 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#981 ci: remove myself from release review
  .github/workflows/create_release.yml
  .github/workflows/release_main.yml
Labels: chore

#986 fix dashboard meta update + fix choropleth color pointer
  src/components/SensorBadges.svelte
  src/data/api.ts
  src/data/meta.ts
  src/data/sensor.ts
  src/formats.ts
  src/specs/mapSpec.ts
Labels: bug

#985 fix: custom license not parsed
  src/data/meta.ts
Labels: bug

#987 export tab flat list of signals
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#989 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore
