Repository cmu-delphi/www-covidcast, pull requests merged in 2021-03, with the labels that each got.

#848 fix: reset highlight region in line chart
  src/components/tooltipUtils.js
  src/modes/mobile/HistoryLineChart.svelte
  src/specs/mapSpec.js
Labels: bug

#682 chore: rename api param to endpoint
  src/data/api.js
Labels: chore

#863 advanced workflows
  .github/release-drafter.yml
  .github/workflows/ci.yml
  .github/workflows/create_release.yml
  .github/workflows/release_main.yml
  .github/workflows/update_gdocs_data.yml
  .release-it.json
  package-lock.json
  package.json
Labels: chore

#870 ci: fix update website job by using common ssh key
  .github/workflows/release_main.yml
Labels: chore

#872 chore: update gdoc links
  netlify.toml
  scripts/generateDescriptions.js
Labels: chore

#881 fix: export tab layout in firefox
  src/modes/exportdata/ExportData.svelte
Labels: bug

#877 Add correlation metrics to the table
  src/data/__test__/testData.js
  src/data/utils.js
  src/data/utils.spec.js
  src/modes/mobile/IndicatorCorrelation.svelte
Labels: enhancement

#885 style: clarify indicator status coverage
  src/modes/indicator-status/IndicatorStatus.svelte
  src/modes/indicator-status/IndicatorStatusTable.svelte
Labels: bug

#886 docs: update release process and contributing guide
  .github/CONTRIBUTING.md
  .gitpod.yml
  README.md
Labels: documentation

#891 ci: use secret token for cross repo access
  .github/workflows/release_main.yml
Labels: chore
