Repository cmu-delphi/www-covidcast, pull requests merged in 2021-12, with the labels that each got.

#1080 add temporary custom annotation for uncertainty
  src/blocks/HistoryLineChart.svelte
  src/components/IndicatorAnnotation.svelte
  src/data/annotations.ts
  src/data/api.ts
  src/specs/lineSpec.ts
Labels: enhancement

#1092 Improve tables
  src/modes/indicator/GeoTable.svelte
  src/modes/summary/IndicatorTable.svelte
  src/styles/mobile.css
Labels: enhancement

#1093 Set default date to -2
  src/stores/constants.ts
  src/stores/index.ts
Labels: enhancement

#1097 Fix search style bug in dashboard
  src/components/RegionSearch.svelte
  src/components/Search.svelte
  src/components/SensorSearch.svelte
  src/components/SensorSourceSearch.svelte
  src/modes/dashboard/config/WidgetPicker.svelte
Labels: bug

#1101 small style tunings
  src/blocks/HistoryLineChart.svelte
  src/blocks/RegionMapWrapper.svelte
Labels: enhancement

#1102 disable maps for google signal
  src/modes/indicator/Indicator.svelte
  src/stores/constants.ts
  src/stores/descriptions.raw.txt
Labels: bug

#1100 improve tooltips
  src/blocks/RegionHexMap.svelte
  src/blocks/RegionMapTooltip.svelte
  src/components/HexGrid/HexGridCell.svelte
Labels: enhancement

#1086 fix State Map for Hospital Admissions
  src/blocks/RegionHexMap.svelte
  src/blocks/RegionMap.svelte
  src/blocks/RegionMapWrapper.svelte
  src/components/KPIChange.svelte
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/stores/constants.ts
Labels: enhancement

#1104 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore
