Repository cmu-delphi/www-covidcast, pull requests merged in 2022-01, with the labels that each got.

#1116 show full date in desktop date picker
  src/components/SensorDatePicker2.svelte
Labels: enhancement

#1119 remove short unit from google signal
  scripts/generateDescriptions.js
  src/data/meta.ts
  src/data/sensor.ts
  src/stores/constants.ts
  src/stores/descriptions.raw.txt
  src/stores/params.ts
  tsconfig.eslint.json
Labels: enhancement

#1115 Mobile Indicator Table
  src/components/SensorBadges.svelte
  src/modes/summary/IndicatorTable.svelte
  src/modes/summary/RowHelper.svelte
  src/styles/mobile.css
Labels: enhancement

#1121 Add inactive source toggle
  src/modes/exportdata/ExportData.svelte
Labels: enhancement

#1114 feat: remove include zero toggle
  src/blocks/HistoryLineChart.svelte
Labels: enhancement

#1106 fix parsing anomalies
  src/data/annotations.ts
Labels: bug

#1107 fix lag sorting
  src/modes/indicator-status/IndicatorStatusTable.svelte
  src/modes/indicator-status/data.ts
Labels: bug

#1124 Change Indicator order
  src/stores/descriptions.raw.txt
Labels: enhancement

#1126 Sorting by relative change
  src/components/SortColumnIndicator.svelte
  src/modes/dashboard/widgets/ATableWidget.svelte
  src/modes/indicator/GeoTable.svelte
Labels: bug

#1127 load "latest" of full time frame
  src/blocks/HistoryLineChart.svelte
  src/blocks/MaxDateHint.svelte
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/modes/survey-results/SurveyQuestion.svelte
Labels: bug

#1130 center beehive toggle + fix links
  src/blocks/RegionMapWrapper.svelte
  src/components/Toggle.svelte
  src/modes/indicator-status/IndicatorSignal.svelte
  src/modes/indicator/Indicator.svelte
  src/modes/summary/Summary.svelte
Labels: bug

#1132 extended scale for covid cases plots
  src/blocks/RegionCountyMap.svelte
  src/blocks/RegionMap.svelte
  src/components/HexGrid/ColorLegend.svelte
  src/components/vega/vegaFactory.ts
  src/data/meta.ts
  src/data/sensor.ts
  src/data/sensorConstants.ts
  src/modes/dashboard/widgets/MapChartWidget.svelte
  src/modes/dashboard/widgets/ZoomedMapChartWidget.svelte
  src/specs/mapSpec.ts
  src/stores/params.ts
Labels: enhancement

#1135 feat: extended color scale generalization
  src/data/meta.ts
  src/data/sensor.ts
  src/stores/constants.ts
  src/stores/descriptions.raw.txt
  src/stores/params.ts
  src/stores/questions.raw.txt
Labels: enhancement

#1142 chore: sync main->dev
  package-lock.json
  package.json
Labels: chore

#1145 Auto merge dev upon release
  .github/workflows/release_main.yml
  .github/workflows/update_gdocs_data.yml
  README.md
Labels: chore

#1146 Derive max date/issue for picker and hint
  src/blocks/MaxDateHint.svelte
  src/components/RegionDatePicker.svelte
  src/components/SensorDatePicker2.svelte
  src/modes/dashboard/Dashboard.svelte
  src/modes/dashboard/DashboardParameters.svelte
  src/modes/indicator/Indicator.svelte
  src/modes/summary/CasesOverview.svelte
  src/modes/summary/Summary.svelte
  src/modes/survey-results/SurveyQuestion.svelte
  src/modes/survey-results/SurveyResults.svelte
  src/stores/DataFetcher.ts
Labels: enhancement

#1140 Quidel Raw Hint
  src/blocks/HistoryLineChart.svelte
  src/components/IndicatorAnnotation.svelte
  src/data/annotations.ts
Labels: enhancement

#1149 fix uncertainty hint for multiple regions
  src/blocks/HistoryLineChart.svelte
  src/specs/lineSpec.ts
Labels: bug
