Repository cmu-delphi/www-covidcast, pull requests merged in 2022-02, with the labels that each got.

#1150 Fetch individual regions separately
  src/stores/DataFetcher.ts
Labels: bug

#1152 Manual sync with main
  package-lock.json
  package.json
Labels: chore

#1161 hotfix: add missing wave details + workaround to prevent in future
  src/stores/descriptions.raw.txt
  src/stores/questions.raw.txt
  src/stores/questions.ts
Labels: bug

#1163 dblclick to select date in sparkline and line chart
  src/blocks/HistoryLineChart.svelte
  src/blocks/IndicatorOverview.svelte
Labels: enhancement
